version: '3'
services:
  okapi:
    build: .
    ports:
      - 9130:9130
    container_name: okapi
    volumes:
      - ./repo:/app/repo
      - ./init.d:/app/init.d
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
  postgres:
    image: "postgres"
    volumes:
      - ./db/init.d/:/docker-entrypoint-initdb.d/
    #   - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 111111
      PGDATA: /var/lib/postgresql/data/pgdata
  redis:
    image: "redis:alpine"
